# Generated by Django 5.0.6 on 2024-10-21 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='key',
        ),
        migrations.AddField(
            model_name='customuser',
            name='final_key',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='purchase_key',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='qr_code',
            field=models.ImageField(blank=True, null=True, upload_to='qr_codes/'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='unique_key',
            field=models.CharField(default='ebf95040023f479ea76c99c9071830ff', editable=False, max_length=64, unique=True),
        ),
    ]
