# Generated by Django 5.0.6 on 2024-10-22 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_customuser_key_customuser_final_key_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='unique_key',
            field=models.CharField(default='05fd429e8c384c3d83caa16766238996', editable=False, max_length=64, unique=True),
        ),
    ]
