# Generated by Django 5.0.6 on 2024-10-22 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_customuser_unique_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='unique_key',
            field=models.CharField(default='514cb8778b124ca49dc93f804dd1e0e8', editable=False, max_length=64, unique=True),
        ),
    ]
