# Generated by Django 5.0.6 on 2024-10-19 17:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('offres', '0003_typeoffre_remove_offre_prix_offre_evenement_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='offre',
            name='evenement',
        ),
    ]
