# Generated by Django 5.0.6 on 2024-10-19 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offres', '0004_remove_offre_evenement'),
    ]

    operations = [
        migrations.AddField(
            model_name='offre',
            name='prix',
            field=models.DecimalField(decimal_places=2, default=10.0, max_digits=10),
        ),
    ]
