# Generated by Django 5.0.6 on 2024-10-19 20:20

from django.db import migrations , models



class Migration(migrations.Migration):

    dependencies = [
        ('offres', '0007_alter_offre_prix'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offre',
            name='prix',
            field=models.DecimalField(max_digits=10, decimal_places=2, default=0.0),
        ),
    ]
