# Generated by Django 5.0.6 on 2024-10-20 22:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('offres', '0008_auto_20241019_2020'),
    ]

    operations = [
        migrations.RenameField(
            model_name='typeoffre',
            old_name='Prix',
            new_name='prix',
        ),
    ]
