# Generated by Django 5.0.6 on 2024-10-20 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offres', '0009_rename_prix_typeoffre_prix'),
    ]

    operations = [
        migrations.AddField(
            model_name='panier',
            name='prix',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
